import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { Logger } from "@bilibili-notify/internal";
import { KeyManager } from "./key-manager";
import { deriveKeyFromPassphrase } from "./secret-box";

/**
 * Resolves the 32-byte AES key used to encrypt at-rest secrets.
 *
 * Two strategies:
 *   - {@link PassphraseKeyProvider} — key scrypt-derived from an injected
 *     passphrase (`bootstrap.cookieEncryptionKey` / `BN_COOKIE_KEY`). The key
 *     itself is NEVER written to disk; only a non-secret per-install salt is.
 *     This is the only mode that gives real at-rest protection.
 *   - {@link FileKeyProvider} — legacy behaviour: a random key file living
 *     next to the ciphertext (auto-generated by {@link KeyManager}). Key and
 *     data co-located → obfuscation, not protection. Kept as the zero-config
 *     fallback.
 */
export interface KeyProvider {
	getKey(): Promise<Buffer>;
	/** Whether the key can be rotated in place. Injected passphrases cannot. */
	readonly resettable: boolean;
	/** Rotate the key (file mode) or, for passphrase mode, just return it unchanged. */
	resetKey(): Promise<Buffer>;
	/** `true` = injected passphrase (real encryption); `false` = co-located key file. */
	readonly protected: boolean;
}

export class FileKeyProvider implements KeyProvider {
	readonly resettable = true;
	readonly protected = false;
	private readonly km: KeyManager;
	private keyPromise: Promise<Buffer> | null = null;
	constructor(keyPath: string, logger: Logger) {
		this.km = new KeyManager(keyPath, logger);
	}
	getKey(): Promise<Buffer> {
		if (this.keyPromise) return this.keyPromise;
		return this.cache(this.km.loadOrCreate());
	}
	resetKey(): Promise<Buffer> {
		return this.cache(this.km.createNew());
	}
	private cache(p: Promise<Buffer>): Promise<Buffer> {
		this.keyPromise = p;
		p.catch(() => {
			if (this.keyPromise === p) this.keyPromise = null;
		});
		return p;
	}
}

export class PassphraseKeyProvider implements KeyProvider {
	readonly resettable = false;
	readonly protected = true;
	private cached: Buffer | null = null;
	constructor(
		private readonly passphrase: string,
		private readonly saltPath: string,
		private readonly logger: Logger,
	) {}

	async getKey(): Promise<Buffer> {
		if (this.cached) return this.cached;
		const salt = await this.loadOrCreateSalt();
		this.cached = deriveKeyFromPassphrase(this.passphrase, salt);
		this.logger.debug("[key] 使用注入密钥派生 AES-256 密钥 (scrypt)");
		return this.cached;
	}

	/** Injected key cannot be rotated — return it unchanged (caller still wipes the ciphertext). */
	resetKey(): Promise<Buffer> {
		return this.getKey();
	}

	private async loadOrCreateSalt(): Promise<Buffer> {
		let hex: string | null = null;
		try {
			hex = (await readFile(this.saltPath, "utf8")).trim();
		} catch (e) {
			if ((e as NodeJS.ErrnoException).code !== "ENOENT") {
				// 文件存在但读不了(EACCES/EIO…):绝不能静默重生成 —— 那会换 key,
				// 把所有用注入密钥加密的 secrets 一次性变为无法解密且无声重登。
				this.logger.error(`[key] kdf.salt 读取失败（非缺失）: ${(e as Error).message}`);
				throw e;
			}
			// ENOENT → 首次运行,正常创建
		}
		if (hex !== null) {
			// 精确 32 位十六进制 = 16 字节(本类只写 randomBytes(16))。放宽到
			// {32,} 会接受被截断/拼接的 salt,静默派生出错 key → 无声重登。
			if (/^[0-9a-f]{32}$/i.test(hex)) return Buffer.from(hex, "hex");
			this.logger.warn(
				"[key] kdf.salt 格式非法（非 32 位十六进制），将重新生成 —— " +
					"既有用注入密钥加密的 secrets（B 站 cookie / AI apiKey）届时无法解密、需重新登录。",
			);
		}
		const salt = randomBytes(16);
		await mkdir(dirname(this.saltPath), { recursive: true });
		// P2:唯一 tmp(pid + rand),对齐他处写盘约定。固定 `${saltPath}.tmp`
		// 在并发首启(两进程同时无 salt)时互相覆盖 tmp → rename 出错乱 salt。
		const tmp = `${this.saltPath}.tmp.${process.pid}.${randomBytes(4).toString("hex")}`;
		await writeFile(tmp, salt.toString("hex"), "utf8");
		try {
			await rename(tmp, this.saltPath);
		} catch (e) {
			await unlink(tmp).catch(() => {});
			throw e;
		}
		return salt;
	}
}

export interface CreateKeyProviderOptions {
	/** Injected passphrase. When present → PassphraseKeyProvider; else FileKeyProvider. */
	passphrase?: string;
	/** Legacy random-key file path (FileKeyProvider). */
	keyPath: string;
	/** Per-install scrypt salt path (PassphraseKeyProvider). */
	saltPath: string;
	logger: Logger;
}

export function createKeyProvider(opts: CreateKeyProviderOptions): KeyProvider {
	const pass = opts.passphrase?.trim();
	if (pass) return new PassphraseKeyProvider(pass, opts.saltPath, opts.logger);
	// 回退选择点统一打高可见告警 —— 此前仅 standalone 的 bootstrap.ts 警示,
	// 任何其它调用方落到回退时静默无声。
	// 文案保持端中立(不提 BN_COOKIE_KEY,那是 standalone 专属);standalone
	// 在 bootstrap 另加可执行指引。
	opts.logger.warn(
		"[key] 未提供注入密钥:secrets（B 站 cookie / AI apiKey）使用本地随机密钥，" +
			"且密钥与密文同目录 —— 仅为混淆，不构成真正的静态加密。",
	);
	return new FileKeyProvider(opts.keyPath, opts.logger);
}
