// AI 服务商注册表。本体在零依赖的 constants(设置页经 /constants 子路径消费),
// 这里给后端消费者补一条根入口的路 —— 与 FEATURE_KEYS 同样的两路一值。
export {
	type ActivePersonaShape,
	AI_PROVIDER_IDS,
	AI_PROVIDERS,
	type AIPersonaShape,
	type AIPresetShape,
	type AIProviderId,
	type AIProviderMeta,
	type AIProviderProfileShape,
	API_FLAVOR_IDS,
	type APIFlavorId,
	BUILTIN_AI_PRESETS,
	colorFromUid,
	countsAsDelivery,
	countsAsFailure,
	DEFAULT_ROAST_SCHEDULE,
	EMPTY_AI_PROVIDER_PROFILE,
	INBOUND_CAPABLE_PLATFORMS,
	inboundGapReason,
	isMirrorPrefix,
	isTargetPaused,
	LINK_LIMITS,
	LINK_REPLY_FORMS,
	type LinkLimits,
	type LinkReplyForm,
	MIRROR_PREFIX_RE,
	PUSH_STATUSES,
	PUSH_TARGET_PLATFORMS,
	platformCanReceiveReply,
	platformSupportsAtAll,
	providerMeta,
	resolveActivePersona,
	resolveAIProfile,
	resolveChatThinkingLevel,
	THINKING_LEVELS,
	type ThinkingLevel,
	UP_COLORS,
	WEB_SEARCH_BACKEND_IDS,
	WEB_SEARCH_BACKENDS,
	type WebSearchBackendId,
	type WebSearchBackendMeta,
	webSearchBackendMeta,
} from "./constants";
export * from "./platform";
export * from "./schema";
export * from "./util";
